packages:
  - docs
  - packages/**

catalog:
  execa: ^9.6.1
  typescript: ^5.9.3
  vite: ^7.3.1

allowBuilds:
  '@biomejs/biome': true
  '@swc/core': false
  esbuild: false
  msw: false
  sharp: false
  svelte-preprocess: false
